# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: VLCTechFest 2019
email: hola@vlctechfest.org
baseurl: "/vlctechfest2019" # the subpath of your site, e.g. /blog
url: "https://vlctechfest.org" # the base hostname & protocol for your site
twitter_username: vlctechfest
github_username:  vlctechhub
hub_url: https://vlctechhub.org/
hub_title: vlctechhub.org
slack_url: https://slack.vlctechhub.org/
slack_title: Chat
path:
  company_images: "images/companies/"
  community_images: "images/communities/"
navigation:
  - info
  - faq
  - contact
  - vtf2018
# Build settings
markdown: kramdown
