# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: VLCTechFest 2019
email: hola@vlctechfest.org
baseurl: ""  # the subpath of your site, e.g. /blog
url: https://vlctechfest.org # the base hostname & protocol for your site
description:
  es: 11 de mayo de 2019. Evento gratuito y abierto a todo el mundo que reúne a las comunidades tecnológicas de la Comunidad Valenciana.
  en: May 11th, 2019. Free and open event for everyone to bring together the technical communities of Valencian Community.
  ca: 11 de maig de 2019. Esdeveniment gratuït i obert a tothom que reuneix les comunitats tecnològiques de la Comunitat Valenciana.
share_image:
  es: vlctechfest2019-cfp-2-1-es.png
  en: vlctechfest2019-cfp-2-1-en.png
  ca: vlctechfest2019-cfp-2-1-ca.png
fest:
  twitter_username: vlctechfest
  youtube_url: https://www.youtube.com/channel/UCS7z_DqAOTqwANFvmKmM5ig
hub:
  twitter_username: vlctechhub
  github_username:  vlctechhub
  web_url: https://vlctechhub.org/
  web_title: vlctechhub.org
  slack_url: https://slack.vlctechhub.org/
  slack_title:
    es: Chat
    en: Chat
    ca: Xat
path:
  images: /images/
  company_images: /images/companies/
  community_images: /images/communities/
navigation:
  - about
  - cfp
  - faq
  - communities
  - vtf2018
locale:
  es: es_ES
  en: en_US
  ca: ca_ES
# Build settings
markdown: kramdown
plugins:
  - jekyll-redirect-from
